function [fitresult, gof] = ImpFitProof(time, fittingWf,eq)
%CREATEFIT(TIME,FITTINGWF)
%  Create a fit.
%
%  Data for 'ImpedanceFit' fit:
%      X Input : time
%      Y Output: fittingWf
%  Output:
%      fitresult : a fit object representing the fit.jira mxwbio
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Mar-2018 14:40:35


%% Fit: 'ImpedanceFit'.
%[xData, yData] = prepareCurveData( time, fittingWf );

% Set up fittype and options.
%ft = fittype( '535+((2.1e-1*Rct)*(1-exp(-time/(Rct*C*1e-4)))+2.1e-6*9.5067e+04)/(3.2226e-3)', 'independent', 'time', 'dependent', 'y' );
ft = fittype( num2str(eq), 'independent', 'time', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.DiffMaxChange = 0.000001;
opts.Display = 'Off';
opts.Lower = [1e-6 1e-5];
opts.MaxIter = 500;
opts.StartPoint = [0.1 1e-3];  % C is in 1e-9, Rct is in 1e9
opts.Upper = [1e2 1e5];

% Fit model to data.
[fitresult, gof] = fit( time', fittingWf, ft, opts );

% Plot fit with data.
figure( 'Name', 'ImpedanceFit' );
h = plot( fitresult, time, fittingWf );
legend( h, 'fittingWf vs. time', 'ImpedanceFit', 'Location', 'NorthEast' );
% Label axes
xlabel('time [s]')
ylabel('Voltage [V]')
grid on


